import "@/styles/globals.css";
import Head from "next/head";
import type { AppProps } from "next/app";
import { JSX } from "react";
export default function App({ Component, pageProps }: AppProps): JSX.Element {
  return (
    <>
     <Head>
        <title>Create Next time</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link key={1} rel="icon" href="/favicon.ico" />
        <h1>Custom header</h1>
      </Head>
      <Component {...pageProps} />
    </>
  );
}
